# Generated by Django 5.1.2 on 2024-10-24 04:20

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDeadlockBuild',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('hero_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalDeadlockBuildCategory',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('item_ids', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='build_editor.localdeadlockbuild')),
            ],
        ),
    ]
